defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  min_messages: WARNING
  username: <your_username>
  password: <your_password_or_remove_this_entire_entry_if_you_dont_have_one>

development:
  <<: *defaults
  database: orlando-walking-tours-rails_development

test:
  <<: *defaults
  database: orlando-walking-tours-rails_test
